build: remove legacy Apple SDK frameworks
According to nixos.org[^1], the `darwin.apple_sdk` frameworks have been
stubs for some time, and are now removed. Evaluating `atuin` on darwin
on `nixpkgs-unstable` results in the following evaluation error:

```
error: darwin.apple_sdk_11_0 has been
  removed as it was a legacy compatibility stub; see
  <https://nixos.org/manual/nixpkgs/stable/#sec-darwin-legacy-frameworks>
  for migration instructions
```

According to those linked docs, the fix is to remove references to these
SDKs, which will not have any other effect since they were stubs anyway.

[^1]: https://nixos.org/manual/nixpkgs/stable/#sec-darwin-legacy-frameworks